FROM node:20-alpine

WORKDIR /app
COPY package*.json ./
RUN npm ci --legacy-peer-deps

EXPOSE 4200
CMD ["npm", "start", "--", "--host", "0.0.0.0", "--poll", "1000", "--proxy-config", "proxy.conf.docker.json"]
