version: '3.8'

services:
  alvorada-api:
    image: bjsoftware/alvorada-api:latest
    container_name: alvorada-api
    restart: always
    environment:
      DATABASE_URL: "postgres://${DB_USER}:${DB_PASS}@${DB_HOST}:${DB_PORT}/${DB_NAME}"
      PORT: "${PORT}"
    networks:
      - network_db
      - network_public

  alvorada-crm:
    image: bjsoftware/alvorada-crm:latest
    container_name: alvorada-crm-app
    restart: always
    depends_on:
      - alvorada-api
    networks:
      - network_db
      - network_public
    deploy:
      placement:
        constraints:
          - node.role == manager
      labels:
        - "traefik.enable=true"
        - "traefik.swarm.network=network_public"
        - "traefik.http.routers.alvorada-crm.rule=Host(`${HOST_URL}`)"
        - "traefik.http.routers.alvorada-crm.entrypoints=websecure"
        - "traefik.http.routers.alvorada-crm.tls.certresolver=letsencryptresolver"
        - "traefik.http.services.alvorada-crm.loadbalancer.server.port=80"

networks:
  network_db:
    external: true
  network_public:
    external: true
